insert into business (id, name, full_address, city, state, stars, review_count, open) values (1, 'Chatterbridge', '26214 Crowley Parkway', 'Albany', 'New York', 3.1, 35, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (2, 'Browsetype', '67429 Northridge Road', 'Bonita Springs', 'Florida', 1.3, 81, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (3, 'Cogilith', '16535 Bashford Trail', 'Dallas', 'Texas', 4.2, 25, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (4, 'Abata', '07721 Declaration Hill', 'Kansas City', 'Missouri', 1.2, 75, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (5, 'Tagchat', '85309 Prairie Rose Point', 'Burbank', 'California', 1.3, 27, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (6, 'Geba', '6 Monica Court', 'Houston', 'Texas', 3.7, 81, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (7, 'Devify', '56 Ohio Lane', 'Stockton', 'California', 4.5, 86, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (8, 'JumpXS', '81 Brentwood Street', 'Austin', 'Texas', 3.6, 33, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (9, 'Zava', '3613 Mitchell Crossing', 'Boston', 'Massachusetts', 2.0, 58, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (10, 'Quatz', '68 Bonner Hill', 'Albuquerque', 'New Mexico', 1.3, 61, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (11, 'Livetube', '4047 Nevada Hill', 'San Francisco', 'California', 2.2, 76, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (12, 'Plambee', '1943 Debra Street', 'Seattle', 'Washington', 4.2, 35, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (13, 'Devpoint', '0567 Sage Way', 'Richmond', 'Virginia', 2.2, 89, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (14, 'Kwimbee', '40831 Brentwood Drive', 'Boise', 'Idaho', 4.0, 79, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (15, 'Brainlounge', '653 Oakridge Road', 'Southfield', 'Michigan', 4.0, 36, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (16, 'Devpoint', '7 Hauk Drive', 'Houston', 'Texas', 2.2, 13, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (17, 'Lazzy', '00527 Straubel Way', 'Tulsa', 'Oklahoma', 1.5, 17, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (18, 'Voolia', '52 Huxley Junction', 'Littleton', 'Colorado', 4.7, 24, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (19, 'Quatz', '64184 Northport Plaza', 'Alexandria', 'Louisiana', 3.6, 67, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (20, 'Riffpath', '8747 Manufacturers Terrace', 'Winston Salem', 'North Carolina', 4.1, 43, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (21, 'Babbleset', '1 Norway Maple Road', 'Eugene', 'Oregon', 1.4, 23, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (22, 'Vidoo', '9152 Hansons Point', 'Sioux Falls', 'South Dakota', 1.7, 80, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (23, 'Quatz', '4503 Sommers Drive', 'Louisville', 'Kentucky', 4.5, 31, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (24, 'Roomm', '346 Gerald Court', 'Hialeah', 'Florida', 4.7, 73, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (25, 'Centizu', '4 Dorton Street', 'Waco', 'Texas', 4.6, 35, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (26, 'Zoomdog', '65 Darwin Crossing', 'Bronx', 'New York', 3.7, 26, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (27, 'Zava', '0 Scoville Trail', 'Fairfax', 'Virginia', 4.0, 22, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (28, 'Gigabox', '915 Schlimgen Lane', 'Huntington Beach', 'California', 3.5, 18, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (29, 'Divape', '222 Mallard Pass', 'Saint Petersburg', 'Florida', 3.2, 12, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (30, 'Edgepulse', '51085 5th Trail', 'Pittsburgh', 'Pennsylvania', 1.1, 5, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (31, 'Yombu', '989 Armistice Avenue', 'North Hollywood', 'California', 4.8, 13, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (32, 'Jabberbean', '25 Thierer Place', 'Colorado Springs', 'Colorado', 2.7, 88, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (33, 'Pixope', '682 Novick Court', 'Rochester', 'New York', 1.6, 4, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (34, 'Skajo', '11620 Carey Plaza', 'Hialeah', 'Florida', 5.0, 24, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (35, 'Rhycero', '33336 Carey Place', 'Reston', 'Virginia', 2.0, 5, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (36, 'Riffwire', '14682 Troy Plaza', 'Tucson', 'Arizona', 1.6, 96, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (37, 'Zava', '93 Crowley Parkway', 'Carson City', 'Nevada', 3.0, 92, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (38, 'Tambee', '3 Grim Terrace', 'Camden', 'New Jersey', 1.4, 79, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (39, 'Flipopia', '755 Green Ridge Trail', 'San Angelo', 'Texas', 2.5, 10, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (40, 'Roomm', '8369 Di Loreto Avenue', 'Houston', 'Texas', 4.9, 67, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (41, 'Ntags', '9112 Ronald Regan Avenue', 'Tampa', 'Florida', 3.3, 7, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (42, 'Ntags', '394 Saint Paul Alley', 'Annapolis', 'Maryland', 1.2, 48, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (43, 'Pixonyx', '10032 Helena Street', 'Jersey City', 'New Jersey', 2.8, 34, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (44, 'Twiyo', '64 Lawn Court', 'Saint Petersburg', 'Florida', 2.3, 9, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (45, 'Trudeo', '4140 Jay Avenue', 'Knoxville', 'Tennessee', 2.7, 13, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (46, 'Demivee', '00683 Sheridan Street', 'Pensacola', 'Florida', 1.8, 71, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (47, 'Shuffletag', '99218 Pleasure Alley', 'Aiken', 'South Carolina', 4.9, 96, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (48, 'Oyoloo', '08 Waywood Place', 'South Bend', 'Indiana', 3.4, 16, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (49, 'Katz', '07 Bluejay Place', 'Washington', 'District of Columbia', 3.7, 89, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (50, 'Skinder', '49796 Cardinal Avenue', 'Washington', 'District of Columbia', 1.6, 58, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (51, 'Zoomdog', '03 Dovetail Point', 'Texarkana', 'Texas', 4.4, 45, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (52, 'Buzzster', '332 Doe Crossing Way', 'Washington', 'District of Columbia', 2.4, 82, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (53, 'Zoomzone', '8 Ruskin Park', 'Chicago', 'Illinois', 2.1, 22, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (54, 'Devcast', '90 Morrow Avenue', 'Seattle', 'Washington', 3.9, 72, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (55, 'Zoomlounge', '512 Cordelia Center', 'Oklahoma City', 'Oklahoma', 2.9, 52, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (56, 'Zoomdog', '200 Montana Plaza', 'Peoria', 'Illinois', 1.8, 15, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (57, 'Bluezoom', '577 Menomonie Alley', 'Savannah', 'Georgia', 3.1, 82, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (58, 'Jabberstorm', '74 Hanover Road', 'Anchorage', 'Alaska', 4.6, 56, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (59, 'Blogtags', '8 5th Avenue', 'Tyler', 'Texas', 1.7, 48, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (60, 'Realblab', '9747 Farmco Street', 'Houston', 'Texas', 3.4, 4, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (61, 'Skajo', '86 Debs Park', 'Tucson', 'Arizona', 2.7, 60, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (62, 'Skidoo', '679 Cody Crossing', 'Portland', 'Oregon', 1.1, 82, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (63, 'Feedbug', '04 Sutherland Crossing', 'Rockville', 'Maryland', 4.3, 4, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (64, 'Topicblab', '074 Reinke Terrace', 'Milwaukee', 'Wisconsin', 1.4, 72, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (65, 'Skiba', '2 Cardinal Alley', 'Boise', 'Idaho', 4.7, 38, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (66, 'Feedfire', '9 Merrick Crossing', 'Amarillo', 'Texas', 4.0, 26, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (67, 'Gabtune', '261 Northport Circle', 'Elizabeth', 'New Jersey', 1.8, 13, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (68, 'Gigaclub', '1343 Derek Terrace', 'San Francisco', 'California', 4.4, 66, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (69, 'Trunyx', '84 Hansons Hill', 'Amarillo', 'Texas', 3.7, 74, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (70, 'Oyondu', '73733 4th Circle', 'Huntington', 'West Virginia', 2.8, 78, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (71, 'Shufflester', '97 Mockingbird Trail', 'Shawnee Mission', 'Kansas', 2.9, 94, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (72, 'Avavee', '2 Autumn Leaf Circle', 'Louisville', 'Kentucky', 3.9, 45, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (73, 'Yakidoo', '24795 Daystar Crossing', 'Seattle', 'Washington', 4.9, 20, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (74, 'Vitz', '183 Armistice Road', 'West Hartford', 'Connecticut', 3.8, 33, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (75, 'Voonyx', '977 Nelson Terrace', 'Anchorage', 'Alaska', 2.0, 96, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (76, 'Latz', '0 Trailsway Avenue', 'Houston', 'Texas', 4.5, 44, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (77, 'Jetwire', '11289 Lindbergh Alley', 'Bridgeport', 'Connecticut', 3.4, 100, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (78, 'Innojam', '8281 Sloan Parkway', 'Denver', 'Colorado', 1.4, 63, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (79, 'Eire', '9276 Rowland Hill', 'Biloxi', 'Mississippi', 4.1, 19, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (80, 'Chatterbridge', '427 Gerald Terrace', 'El Paso', 'Texas', 1.5, 31, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (81, 'Riffwire', '82970 4th Trail', 'Richmond', 'Virginia', 4.6, 45, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (82, 'Zoombox', '15 Scofield Circle', 'Las Vegas', 'Nevada', 3.9, 42, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (83, 'Devpoint', '6 Oakridge Pass', 'Missoula', 'Montana', 3.9, 19, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (84, 'Shuffletag', '79 Maryland Pass', 'Las Vegas', 'Nevada', 3.2, 20, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (85, 'Tagtune', '363 Armistice Park', 'Trenton', 'New Jersey', 2.4, 50, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (86, 'Oodoo', '5 Warbler Park', 'Kansas City', 'Missouri', 1.5, 80, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (87, 'Shuffledrive', '6 Granby Hill', 'Winter Haven', 'Florida', 4.8, 46, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (88, 'Quaxo', '6 Bluejay Junction', 'Washington', 'District of Columbia', 3.7, 61, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (89, 'Omba', '9187 Oakridge Terrace', 'Houston', 'Texas', 3.8, 59, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (90, 'Buzzshare', '84981 Sunnyside Parkway', 'Cleveland', 'Ohio', 3.2, 8, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (91, 'Miboo', '1073 Fallview Road', 'Odessa', 'Texas', 2.0, 65, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (92, 'Mycat', '1133 Raven Point', 'Topeka', 'Kansas', 3.0, 25, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (93, 'Jaxbean', '0 Arkansas Avenue', 'Savannah', 'Georgia', 3.8, 37, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (94, 'Skyble', '344 Debs Circle', 'Cincinnati', 'Ohio', 1.1, 43, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (95, 'Teklist', '13091 Parkside Crossing', 'Amarillo', 'Texas', 2.9, 17, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (96, 'Mynte', '149 Monica Park', 'Brooklyn', 'New York', 1.9, 14, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (97, 'Skyble', '34 Melby Hill', 'Boca Raton', 'Florida', 4.5, 25, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (98, 'Geba', '6892 Everett Point', 'Winston Salem', 'North Carolina', 3.5, 69, true);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (99, 'Skippad', '6 Gulseth Avenue', 'Chicago', 'Illinois', 1.9, 44, false);
insert into business (id, name, full_address, city, state, stars, review_count, open) values (100, 'Tagpad', '2 Transport Parkway', 'Atlanta', 'Georgia', 3.7, 75, true);
