function pose = clothoid2Pose(rho,drho,s,theta)
z = matlabshared.tracking.internal.scenario.fresnelg( ...
                    s, ...
                    drho, ...
                    rho, ...
                    theta);
pose = [real(z), imag(z), s*rho+s.*s/2*drho];

end

